/*
 * This source file was generated by the Gradle 'init' task
 */
package org.engine;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void VentilleLesAssets() {
        assertEquals("Assertif", "Assertif");
    }
}
